#!/bin/bash

set -o errexit
set -o nounset


echo 'STARTING START'

worker_ready(){
    celery -A books_api.celery inspect ping
}

until worker_ready; do

    echo 'Celery workers not available :('
    sleep 1

done

echo 'Celery workers are available and ready!... :)'

exec celery \
    -A books_api.celery \
    -b "${CELERY_BROKER}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_***REMOVED***}"