# Generated by Django 4.1.7 on 2023-10-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0004_remove_book_release_date_book_release_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=17, unique=True, verbose_name="ISBN"),
        ),
    ]
