# Generated by Django 4.1.7 on 2023-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0005_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="last name"),
        ),
    ]
