# Generated by Django 4.1.7 on 2023-09-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="published_books",
                to="recommender.publisher",
                verbose_name="publisher",
            ),
        ),
    ]
