# Generated by Django 4.1.7 on 2023-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=3, verbose_name="average rating"
            ),
        ),
    ]
