# Generated by Django 4.1.7 on 2023-10-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0002_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="published_books",
                to="recommender.publisher",
                verbose_name="publisher",
            ),
        ),
    ]
