# Generated by Django 4.1.7 on 2023-10-01 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0003_alter_book_description_alter_book_publisher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="release_date",
        ),
        migrations.AddField(
            model_name="book",
            name="release_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="release_year",
            ),
        ),
    ]
