# Generated by Django 4.1.7 on 2023-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0007_remove_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="description"
            ),
        ),
    ]
