# Generated by Django 4.1.7 on 2023-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about_me",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter_handle",
        ),
        migrations.AddField(
            model_name="profile",
            name="searched_books",
            field=models.ManyToManyField(
                blank=True, related_name="searched", to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_born",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Birth Year"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="Not set",
                max_length=20,
                verbose_name="gender",
            ),
        ),
    ]
