# Generated by Django 4.1.7 on 2023-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0008_book_description"),
        ("profiles", "0002_remove_profile_about_me_remove_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="searched_books",
            field=models.ManyToManyField(
                blank=True, related_name="searched", to="recommender.book"
            ),
        ),
    ]
